java -cp . connectx.CXPlayerTester 4 4 4 connectx.IDPlayer.IDPlayer connectx.L0.L0 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 4 4 connectx.IDPlayer.IDPlayer connectx.L0.L0 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 4 4 connectx.IDPlayer.IDPlayer connectx.L0.L0 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 4 4 connectx.IDPlayer.IDPlayer connectx.L0.L0 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 5 4 connectx.IDPlayer.IDPlayer connectx.L0.L0 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 5 4 connectx.IDPlayer.IDPlayer connectx.L0.L0 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 5 4 connectx.IDPlayer.IDPlayer connectx.L0.L0 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 5 4 connectx.IDPlayer.IDPlayer connectx.L0.L0 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 6 4 connectx.IDPlayer.IDPlayer connectx.L0.L0 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 6 4 connectx.IDPlayer.IDPlayer connectx.L0.L0 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 6 4 connectx.IDPlayer.IDPlayer connectx.L0.L0 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 6 4 connectx.IDPlayer.IDPlayer connectx.L0.L0 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 7 4 connectx.IDPlayer.IDPlayer connectx.L0.L0 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 7 4 connectx.IDPlayer.IDPlayer connectx.L0.L0 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 7 4 connectx.IDPlayer.IDPlayer connectx.L0.L0 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 7 4 connectx.IDPlayer.IDPlayer connectx.L0.L0 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 4 5 connectx.IDPlayer.IDPlayer connectx.L0.L0 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 4 5 connectx.IDPlayer.IDPlayer connectx.L0.L0 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 4 5 connectx.IDPlayer.IDPlayer connectx.L0.L0 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 5 5 connectx.IDPlayer.IDPlayer connectx.L0.L0 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 5 5 connectx.IDPlayer.IDPlayer connectx.L0.L0 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 5 5 connectx.IDPlayer.IDPlayer connectx.L0.L0 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 5 5 connectx.IDPlayer.IDPlayer connectx.L0.L0 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 6 5 connectx.IDPlayer.IDPlayer connectx.L0.L0 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 6 5 connectx.IDPlayer.IDPlayer connectx.L0.L0 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 6 5 connectx.IDPlayer.IDPlayer connectx.L0.L0 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 6 5 connectx.IDPlayer.IDPlayer connectx.L0.L0 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 7 5 connectx.IDPlayer.IDPlayer connectx.L0.L0 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 7 5 connectx.IDPlayer.IDPlayer connectx.L0.L0 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 7 5 connectx.IDPlayer.IDPlayer connectx.L0.L0 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 7 5 connectx.IDPlayer.IDPlayer connectx.L0.L0 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 20 20 10 connectx.IDPlayer.IDPlayer connectx.L0.L0 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 30 30 10 connectx.IDPlayer.IDPlayer connectx.L0.L0 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 40 40 10 connectx.IDPlayer.IDPlayer connectx.L0.L0 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 50 50 10 connectx.IDPlayer.IDPlayer connectx.L0.L0 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 4 4 connectx.IDPlayer.IDPlayer connectx.L1.L1 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 4 4 connectx.IDPlayer.IDPlayer connectx.L1.L1 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 4 4 connectx.IDPlayer.IDPlayer connectx.L1.L1 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 4 4 connectx.IDPlayer.IDPlayer connectx.L1.L1 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 5 4 connectx.IDPlayer.IDPlayer connectx.L1.L1 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 5 4 connectx.IDPlayer.IDPlayer connectx.L1.L1 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 5 4 connectx.IDPlayer.IDPlayer connectx.L1.L1 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 5 4 connectx.IDPlayer.IDPlayer connectx.L1.L1 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 6 4 connectx.IDPlayer.IDPlayer connectx.L1.L1 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 6 4 connectx.IDPlayer.IDPlayer connectx.L1.L1 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 6 4 connectx.IDPlayer.IDPlayer connectx.L1.L1 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 6 4 connectx.IDPlayer.IDPlayer connectx.L1.L1 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 7 4 connectx.IDPlayer.IDPlayer connectx.L1.L1 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 7 4 connectx.IDPlayer.IDPlayer connectx.L1.L1 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 7 4 connectx.IDPlayer.IDPlayer connectx.L1.L1 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 7 4 connectx.IDPlayer.IDPlayer connectx.L1.L1 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 4 5 connectx.IDPlayer.IDPlayer connectx.L1.L1 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 4 5 connectx.IDPlayer.IDPlayer connectx.L1.L1 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 4 5 connectx.IDPlayer.IDPlayer connectx.L1.L1 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 5 5 connectx.IDPlayer.IDPlayer connectx.L1.L1 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 5 5 connectx.IDPlayer.IDPlayer connectx.L1.L1 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 5 5 connectx.IDPlayer.IDPlayer connectx.L1.L1 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 5 5 connectx.IDPlayer.IDPlayer connectx.L1.L1 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 6 5 connectx.IDPlayer.IDPlayer connectx.L1.L1 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 6 5 connectx.IDPlayer.IDPlayer connectx.L1.L1 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 6 5 connectx.IDPlayer.IDPlayer connectx.L1.L1 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 6 5 connectx.IDPlayer.IDPlayer connectx.L1.L1 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 7 5 connectx.IDPlayer.IDPlayer connectx.L1.L1 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 7 5 connectx.IDPlayer.IDPlayer connectx.L1.L1 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 7 5 connectx.IDPlayer.IDPlayer connectx.L1.L1 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 7 5 connectx.IDPlayer.IDPlayer connectx.L1.L1 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 20 20 10 connectx.IDPlayer.IDPlayer connectx.L1.L1 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 30 30 10 connectx.IDPlayer.IDPlayer connectx.L1.L1 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 40 40 10 connectx.IDPlayer.IDPlayer connectx.L1.L1 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 50 50 10 connectx.IDPlayer.IDPlayer connectx.L1.L1 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 4 4 connectx.IDPlayer.IDPlayer connectx.L2.L2 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 4 4 connectx.IDPlayer.IDPlayer connectx.L2.L2 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 4 4 connectx.IDPlayer.IDPlayer connectx.L2.L2 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 4 4 connectx.IDPlayer.IDPlayer connectx.L2.L2 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 5 4 connectx.IDPlayer.IDPlayer connectx.L2.L2 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 5 4 connectx.IDPlayer.IDPlayer connectx.L2.L2 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 5 4 connectx.IDPlayer.IDPlayer connectx.L2.L2 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 5 4 connectx.IDPlayer.IDPlayer connectx.L2.L2 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 6 4 connectx.IDPlayer.IDPlayer connectx.L2.L2 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 6 4 connectx.IDPlayer.IDPlayer connectx.L2.L2 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 6 4 connectx.IDPlayer.IDPlayer connectx.L2.L2 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 6 4 connectx.IDPlayer.IDPlayer connectx.L2.L2 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 7 4 connectx.IDPlayer.IDPlayer connectx.L2.L2 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 7 4 connectx.IDPlayer.IDPlayer connectx.L2.L2 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 7 4 connectx.IDPlayer.IDPlayer connectx.L2.L2 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 7 4 connectx.IDPlayer.IDPlayer connectx.L2.L2 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 4 5 connectx.IDPlayer.IDPlayer connectx.L2.L2 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 4 5 connectx.IDPlayer.IDPlayer connectx.L2.L2 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 4 5 connectx.IDPlayer.IDPlayer connectx.L2.L2 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 5 5 connectx.IDPlayer.IDPlayer connectx.L2.L2 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 5 5 connectx.IDPlayer.IDPlayer connectx.L2.L2 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 5 5 connectx.IDPlayer.IDPlayer connectx.L2.L2 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 5 5 connectx.IDPlayer.IDPlayer connectx.L2.L2 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 6 5 connectx.IDPlayer.IDPlayer connectx.L2.L2 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 6 5 connectx.IDPlayer.IDPlayer connectx.L2.L2 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 6 5 connectx.IDPlayer.IDPlayer connectx.L2.L2 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 6 5 connectx.IDPlayer.IDPlayer connectx.L2.L2 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 7 5 connectx.IDPlayer.IDPlayer connectx.L2.L2 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 7 5 connectx.IDPlayer.IDPlayer connectx.L2.L2 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 7 5 connectx.IDPlayer.IDPlayer connectx.L2.L2 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 7 5 connectx.IDPlayer.IDPlayer connectx.L2.L2 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 20 20 10 connectx.IDPlayer.IDPlayer connectx.L2.L2 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 30 30 10 connectx.IDPlayer.IDPlayer connectx.L2.L2 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 40 40 10 connectx.IDPlayer.IDPlayer connectx.L2.L2 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 40 40 10 connectx.IDPlayer.IDPlayer connectx.L2.L2 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 4 4 connectx.IDPlayer.IDPlayer connectx.L3.L3 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 4 4 connectx.IDPlayer.IDPlayer connectx.L3.L3 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 4 4 connectx.IDPlayer.IDPlayer connectx.L3.L3 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 4 4 connectx.IDPlayer.IDPlayer connectx.L3.L3 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 5 4 connectx.IDPlayer.IDPlayer connectx.L3.L3 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 5 4 connectx.IDPlayer.IDPlayer connectx.L3.L3 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 5 4 connectx.IDPlayer.IDPlayer connectx.L3.L3 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 5 4 connectx.IDPlayer.IDPlayer connectx.L3.L3 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 6 4 connectx.IDPlayer.IDPlayer connectx.L3.L3 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 6 4 connectx.IDPlayer.IDPlayer connectx.L3.L3 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 6 4 connectx.IDPlayer.IDPlayer connectx.L3.L3 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 6 4 connectx.IDPlayer.IDPlayer connectx.L3.L3 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 7 4 connectx.IDPlayer.IDPlayer connectx.L3.L3 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 7 4 connectx.IDPlayer.IDPlayer connectx.L3.L3 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 7 4 connectx.IDPlayer.IDPlayer connectx.L3.L3 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 7 4 connectx.IDPlayer.IDPlayer connectx.L3.L3 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 4 5 connectx.IDPlayer.IDPlayer connectx.L3.L3 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 4 5 connectx.IDPlayer.IDPlayer connectx.L3.L3 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 4 5 connectx.IDPlayer.IDPlayer connectx.L3.L3 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 5 5 connectx.IDPlayer.IDPlayer connectx.L3.L3 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 5 5 connectx.IDPlayer.IDPlayer connectx.L3.L3 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 5 5 connectx.IDPlayer.IDPlayer connectx.L3.L3 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 5 5 connectx.IDPlayer.IDPlayer connectx.L3.L3 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 6 5 connectx.IDPlayer.IDPlayer connectx.L3.L3 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 6 5 connectx.IDPlayer.IDPlayer connectx.L3.L3 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 6 5 connectx.IDPlayer.IDPlayer connectx.L3.L3 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 6 5 connectx.IDPlayer.IDPlayer connectx.L3.L3 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 7 5 connectx.IDPlayer.IDPlayer connectx.L3.L3 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 7 5 connectx.IDPlayer.IDPlayer connectx.L3.L3 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 7 5 connectx.IDPlayer.IDPlayer connectx.L3.L3 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 7 5 connectx.IDPlayer.IDPlayer connectx.L3.L3 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 20 20 10 connectx.IDPlayer.IDPlayer connectx.L3.L3 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 30 30 10 connectx.IDPlayer.IDPlayer connectx.L3.L3 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 40 40 10 connectx.IDPlayer.IDPlayer connectx.L3.L3 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 50 50 10 connectx.IDPlayer.IDPlayer connectx.L3.L3 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 4 4 connectx.IDPlayer.IDPlayer connectx.L4.L4 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 4 4 connectx.IDPlayer.IDPlayer connectx.L4.L4 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 4 4 connectx.IDPlayer.IDPlayer connectx.L4.L4 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 4 4 connectx.IDPlayer.IDPlayer connectx.L4.L4 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 5 4 connectx.IDPlayer.IDPlayer connectx.L4.L4 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 5 4 connectx.IDPlayer.IDPlayer connectx.L4.L4 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 5 4 connectx.IDPlayer.IDPlayer connectx.L4.L4 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 5 4 connectx.IDPlayer.IDPlayer connectx.L4.L4 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 6 4 connectx.IDPlayer.IDPlayer connectx.L4.L4 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 6 4 connectx.IDPlayer.IDPlayer connectx.L4.L4 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 6 4 connectx.IDPlayer.IDPlayer connectx.L4.L4 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 6 4 connectx.IDPlayer.IDPlayer connectx.L4.L4 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 7 4 connectx.IDPlayer.IDPlayer connectx.L4.L4 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 7 4 connectx.IDPlayer.IDPlayer connectx.L4.L4 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 7 4 connectx.IDPlayer.IDPlayer connectx.L4.L4 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 7 4 connectx.IDPlayer.IDPlayer connectx.L4.L4 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 4 5 connectx.IDPlayer.IDPlayer connectx.L4.L4 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 4 5 connectx.IDPlayer.IDPlayer connectx.L4.L4 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 4 5 connectx.IDPlayer.IDPlayer connectx.L4.L4 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 5 5 connectx.IDPlayer.IDPlayer connectx.L4.L4 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 5 5 connectx.IDPlayer.IDPlayer connectx.L4.L4 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 5 5 connectx.IDPlayer.IDPlayer connectx.L4.L4 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 5 5 connectx.IDPlayer.IDPlayer connectx.L4.L4 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 6 5 connectx.IDPlayer.IDPlayer connectx.L4.L4 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 6 5 connectx.IDPlayer.IDPlayer connectx.L4.L4 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 6 5 connectx.IDPlayer.IDPlayer connectx.L4.L4 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 6 5 connectx.IDPlayer.IDPlayer connectx.L4.L4 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 7 5 connectx.IDPlayer.IDPlayer connectx.L4.L4 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 7 5 connectx.IDPlayer.IDPlayer connectx.L4.L4 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 7 5 connectx.IDPlayer.IDPlayer connectx.L4.L4 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 7 5 connectx.IDPlayer.IDPlayer connectx.L4.L4 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 20 20 10 connectx.IDPlayer.IDPlayer connectx.L4.L4 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 30 30 10 connectx.IDPlayer.IDPlayer connectx.L4.L4 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 40 40 10 connectx.IDPlayer.IDPlayer connectx.L4.L4 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 50 50 10 connectx.IDPlayer.IDPlayer connectx.L4.L4 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 4 4 connectx.IDPlayer.IDPlayer connectx.L5.L5 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 4 4 connectx.IDPlayer.IDPlayer connectx.L5.L5 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 4 4 connectx.IDPlayer.IDPlayer connectx.L5.L5 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 4 4 connectx.IDPlayer.IDPlayer connectx.L5.L5 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 5 4 connectx.IDPlayer.IDPlayer connectx.L5.L5 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 5 4 connectx.IDPlayer.IDPlayer connectx.L5.L5 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 5 4 connectx.IDPlayer.IDPlayer connectx.L5.L5 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 5 4 connectx.IDPlayer.IDPlayer connectx.L5.L5 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 6 4 connectx.IDPlayer.IDPlayer connectx.L5.L5 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 6 4 connectx.IDPlayer.IDPlayer connectx.L5.L5 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 6 4 connectx.IDPlayer.IDPlayer connectx.L5.L5 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 6 4 connectx.IDPlayer.IDPlayer connectx.L5.L5 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 7 4 connectx.IDPlayer.IDPlayer connectx.L5.L5 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 7 4 connectx.IDPlayer.IDPlayer connectx.L5.L5 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 7 4 connectx.IDPlayer.IDPlayer connectx.L5.L5 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 7 4 connectx.IDPlayer.IDPlayer connectx.L5.L5 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 4 5 connectx.IDPlayer.IDPlayer connectx.L5.L5 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 4 5 connectx.IDPlayer.IDPlayer connectx.L5.L5 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 4 5 connectx.IDPlayer.IDPlayer connectx.L5.L5 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 5 5 connectx.IDPlayer.IDPlayer connectx.L5.L5 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 5 5 connectx.IDPlayer.IDPlayer connectx.L5.L5 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 5 5 connectx.IDPlayer.IDPlayer connectx.L5.L5 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 5 5 connectx.IDPlayer.IDPlayer connectx.L5.L5 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 6 5 connectx.IDPlayer.IDPlayer connectx.L5.L5 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 6 5 connectx.IDPlayer.IDPlayer connectx.L5.L5 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 6 5 connectx.IDPlayer.IDPlayer connectx.L5.L5 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 6 5 connectx.IDPlayer.IDPlayer connectx.L5.L5 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 7 5 connectx.IDPlayer.IDPlayer connectx.L5.L5 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 7 5 connectx.IDPlayer.IDPlayer connectx.L5.L5 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 7 5 connectx.IDPlayer.IDPlayer connectx.L5.L5 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 7 5 connectx.IDPlayer.IDPlayer connectx.L5.L5 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 20 20 10 connectx.IDPlayer.IDPlayer connectx.L5.L5 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 30 30 10 connectx.IDPlayer.IDPlayer connectx.L5.L5 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 40 40 10 connectx.IDPlayer.IDPlayer connectx.L5.L5 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 50 50 10 connectx.IDPlayer.IDPlayer connectx.L5.L5 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 4 4 connectx.IDPlayer.IDPlayer connectx.L6.L6 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 4 4 connectx.IDPlayer.IDPlayer connectx.L6.L6 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 4 4 connectx.IDPlayer.IDPlayer connectx.L6.L6 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 4 4 connectx.IDPlayer.IDPlayer connectx.L6.L6 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 5 4 connectx.IDPlayer.IDPlayer connectx.L6.L6 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 5 4 connectx.IDPlayer.IDPlayer connectx.L6.L6 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 5 4 connectx.IDPlayer.IDPlayer connectx.L6.L6 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 5 4 connectx.IDPlayer.IDPlayer connectx.L6.L6 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 6 4 connectx.IDPlayer.IDPlayer connectx.L6.L6 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 6 4 connectx.IDPlayer.IDPlayer connectx.L6.L6 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 6 4 connectx.IDPlayer.IDPlayer connectx.L6.L6 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 6 4 connectx.IDPlayer.IDPlayer connectx.L6.L6 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 7 4 connectx.IDPlayer.IDPlayer connectx.L6.L6 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 7 4 connectx.IDPlayer.IDPlayer connectx.L6.L6 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 7 4 connectx.IDPlayer.IDPlayer connectx.L6.L6 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 7 4 connectx.IDPlayer.IDPlayer connectx.L6.L6 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 4 5 connectx.IDPlayer.IDPlayer connectx.L6.L6 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 4 5 connectx.IDPlayer.IDPlayer connectx.L6.L6 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 4 5 connectx.IDPlayer.IDPlayer connectx.L6.L6 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 5 5 connectx.IDPlayer.IDPlayer connectx.L6.L6 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 5 5 connectx.IDPlayer.IDPlayer connectx.L6.L6 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 5 5 connectx.IDPlayer.IDPlayer connectx.L6.L6 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 5 5 connectx.IDPlayer.IDPlayer connectx.L6.L6 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 6 5 connectx.IDPlayer.IDPlayer connectx.L6.L6 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 6 5 connectx.IDPlayer.IDPlayer connectx.L6.L6 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 6 5 connectx.IDPlayer.IDPlayer connectx.L6.L6 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 6 5 connectx.IDPlayer.IDPlayer connectx.L6.L6 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 4 7 5 connectx.IDPlayer.IDPlayer connectx.L6.L6 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 5 7 5 connectx.IDPlayer.IDPlayer connectx.L6.L6 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 6 7 5 connectx.IDPlayer.IDPlayer connectx.L6.L6 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 7 7 5 connectx.IDPlayer.IDPlayer connectx.L6.L6 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 20 20 10 connectx.IDPlayer.IDPlayer connectx.L6.L6 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 30 30 10 connectx.IDPlayer.IDPlayer connectx.L6.L6 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 40 40 10 connectx.IDPlayer.IDPlayer connectx.L6.L6 -r 2 >> results.txt
java -cp . connectx.CXPlayerTester 50 50 10 connectx.IDPlayer.IDPlayer connectx.L6.L6 -r 2 >> results.txt